defmodule ChatApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :chat_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_chat_api_key",
    signing_salt: "E50r9lc/",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # V2 only: client must send vsn=2.0.0 and message as array [join_ref, ref, topic, event, payload]
  socket "/socket", ChatApiWeb.UserSocket,
    websocket: [
      serializer: [{Phoenix.Socket.V2.JSONSerializer, "~> 2.0.0"}]
    ],
    longpoll: false

  # In dev, avoid serving cached CSS so Tailwind-built app.css is always fresh.
  if code_reloading? do
    plug ChatApiWeb.Plugs.NoCacheAssets
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :chat_api,
    gzip: not code_reloading?,
    only: ChatApiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ChatApiWeb.Router
end
